/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.fabiyjose.practicse5colors;

import java.awt.event.ItemEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Fabián
 */
public class Practicse5Colors extends javax.swing.JFrame {

    /**
     * Creates new form practica5
     */
    
    private boolean red = true;
    private boolean blue = true;
    private boolean green = true;
    private boolean all = true;
    private boolean end = true;
    
    public Practicse5Colors() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        checkRed.setSelected(red);
        checkGreen.setSelected(green); 
        checkBlue.setSelected(blue);
        checkAll.setSelected(all);
        btTopRight.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        positionButton = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        btTopLeft = new javax.swing.JRadioButton();
        btTopRight = new javax.swing.JRadioButton();
        btBottomLeft = new javax.swing.JRadioButton();
        btBottomRight = new javax.swing.JRadioButton();
        checkRed = new javax.swing.JCheckBox();
        checkGreen = new javax.swing.JCheckBox();
        checkBlue = new javax.swing.JCheckBox();
        checkAll = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        try {
            canvas = new com.fabiyjose.practicse5colors.Canvas();
        } catch (java.net.MalformedURLException e1) {
            e1.printStackTrace();
        } catch (java.io.IOException e2) {
            e2.printStackTrace();
        }
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Configuration", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("MV Boli", 1, 18))); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(381, 175));

        positionButton.add(btTopLeft);
        btTopLeft.setText("↖");
        btTopLeft.setToolTipText("Top Left");
        btTopLeft.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                btTopLeftItemStateChanged(evt);
            }
        });

        positionButton.add(btTopRight);
        btTopRight.setText("↗");
        btTopRight.setToolTipText("Top Right");
        btTopRight.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                btTopRightItemStateChanged(evt);
            }
        });

        positionButton.add(btBottomLeft);
        btBottomLeft.setText("↙");
        btBottomLeft.setToolTipText("Bottom Left");
        btBottomLeft.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                btBottomLeftItemStateChanged(evt);
            }
        });

        positionButton.add(btBottomRight);
        btBottomRight.setText("↘");
        btBottomRight.setToolTipText("Bottom Right");
        btBottomRight.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                btBottomRightItemStateChanged(evt);
            }
        });

        checkRed.setText("Red");
        checkRed.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkRedItemStateChanged(evt);
            }
        });

        checkGreen.setText("Green");
        checkGreen.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkGreenItemStateChanged(evt);
            }
        });

        checkBlue.setText("Blue");
        checkBlue.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkBlueItemStateChanged(evt);
            }
        });

        checkAll.setText("All");
        checkAll.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkAllItemStateChanged(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("LOGO POSITION");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("COLOUR FILTER");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkRed)
                            .addComponent(checkBlue))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkAll)
                            .addComponent(checkGreen)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 155, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btBottomLeft)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btBottomRight))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btTopLeft)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btTopRight))
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(82, 82, 82))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkRed)
                    .addComponent(checkGreen))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkBlue)
                    .addComponent(checkAll))
                .addGap(30, 30, 30))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btTopLeft)
                    .addComponent(btTopRight))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btBottomLeft)
                    .addComponent(btBottomRight))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Image", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("MV Boli", 1, 18))); // NOI18N

        javax.swing.GroupLayout canvasLayout = new javax.swing.GroupLayout(canvas);
        canvas.setLayout(canvasLayout);
        canvasLayout.setHorizontalGroup(
            canvasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        canvasLayout.setVerticalGroup(
            canvasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 389, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(canvas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(canvas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel1.setText("© José María & Fabián");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void checkAllItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkAllItemStateChanged
        if (!end) return;
        
        int select = evt.getStateChange();
        if (select == ItemEvent.SELECTED){
            all = true;
            blue = true; checkBlue.setSelected(blue);
            green = true; checkGreen.setSelected(green);
            red = true; checkRed.setSelected(red);
        }else{
            all = false;
            blue = false; checkBlue.setSelected(blue);
            green = false; checkGreen.setSelected(green);
            red = true; checkRed.setSelected(red); //Default color channel
        }
        canvas.paintIt(red, green, blue);
    }//GEN-LAST:event_checkAllItemStateChanged

    
    private void checkGreenItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkGreenItemStateChanged
        int state = evt.getStateChange();
        this.green = state == ItemEvent.SELECTED;
        
        if (!(this.red || this.green || this.blue)){
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "One colour channel must be selected", "One Colour", JOptionPane.INFORMATION_MESSAGE);
            this.green = true; checkGreen.setSelected(green);
        }
        assign(state);
    }//GEN-LAST:event_checkGreenItemStateChanged

    private void checkRedItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkRedItemStateChanged
        int state = evt.getStateChange();
        this.red = state == ItemEvent.SELECTED;
        
        if (!(this.red || this.green || this.blue)){
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "One colour channel must be selected", "One Colour", JOptionPane.INFORMATION_MESSAGE);
            this.red = true; checkRed.setSelected(red);
        }
        assign(state);
    }//GEN-LAST:event_checkRedItemStateChanged

    private void checkBlueItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkBlueItemStateChanged
        int state = evt.getStateChange();
        this.blue = state == ItemEvent.SELECTED;
        
        if (!(this.red || this.green || this.blue)){
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "One colour channel must be selected", "One Colour", JOptionPane.INFORMATION_MESSAGE);
            this.blue = true; checkBlue.setSelected(blue);
        }
        
        assign(state);
    }//GEN-LAST:event_checkBlueItemStateChanged

    private void btTopLeftItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_btTopLeftItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) canvas.setPositionLogo(0);
    }//GEN-LAST:event_btTopLeftItemStateChanged

    private void btTopRightItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_btTopRightItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) canvas.setPositionLogo(1);
    }//GEN-LAST:event_btTopRightItemStateChanged

    private void btBottomLeftItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_btBottomLeftItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) canvas.setPositionLogo(2);
    }//GEN-LAST:event_btBottomLeftItemStateChanged

    private void btBottomRightItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_btBottomRightItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) canvas.setPositionLogo(3);
    }//GEN-LAST:event_btBottomRightItemStateChanged
    
    
    private void assign(int state){
        if (state == ItemEvent.SELECTED){
            if (red && green && blue){
                end = false;
                all = true; checkAll.setSelected(all);
                end = true;
            }
        }else{
            if (all){
                end = false;
                all = false; checkAll.setSelected(all);
                end = true;
            }
        }
        canvas.paintIt(red, green, blue);
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Practicse5Colors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Practicse5Colors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Practicse5Colors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Practicse5Colors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Practicse5Colors().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btBottomLeft;
    private javax.swing.JRadioButton btBottomRight;
    private javax.swing.JRadioButton btTopLeft;
    private javax.swing.JRadioButton btTopRight;
    private com.fabiyjose.practicse5colors.Canvas canvas;
    private javax.swing.JCheckBox checkAll;
    private javax.swing.JCheckBox checkBlue;
    private javax.swing.JCheckBox checkGreen;
    private javax.swing.JCheckBox checkRed;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.ButtonGroup positionButton;
    // End of variables declaration//GEN-END:variables
}
